### ISSUE TITLE
Date range arrows dont' adapt to day height change

### ISSUE THREAD

**Issue by cjayyy** [easepick/easepick#19]
**Describe the bug**
When using range plugin and changing day cell `height`, the date range pseudo arrows don't adjust it's `top` position.

![Screen Shot 2022-04-01 at 11 24 39](https://user-images.githubusercontent.com/14090214/161245674-965c1d7e-6a89-48f2-a0b5-73855be85e15.png)

**To Reproduce**
1. Turn on `RangePlugin`
2. Pass this style variable (along with core styles): `--day-height: 25px;`
3. Open date picker and select some range
4. See range arrows misaligned (not in center vertically)

**Expected behavior**
Range arrows should center align itself dynamically even if cell height is changed.

**Additional context**
When completely removing the `top` parameter from pseudo element arrows it seems to adjust just fine. Is this parameter even necessary?

```css
.container.range-plugin .calendar>.days-grid>.day.start:after {
    border: 8px solid transparent;
    border-left: 8px solid var(--primary-color);
    content: "";
    pointer-events: none;
    position: absolute;
    right: -14px;
    /* top: 11px; <-- disabled this style */
    z-index: 1;
}
```
